In [1]:
# спочатку song_listened
import pandas as pd

path_to_train = './data/train.csv'

cols = ['context_type', 'media_duration', 'user_gender', 'user_age']

train = pd.read_csv(path_to_train, encoding='utf-8', usecols=cols+['listen_type', 'ts_listen', 'user_id', 'is_listened'])
train = train.sort_values(by=['ts_listen'], axis=0)

train.head()

,ts_listen,context_type,media_duration,user_gender,user_id,user_age,is_listened
5010516,1,0,454,0,4606,23,0
1309460,2,0,213,0,7557,28,1
824607,2,0,235,0,5034,19,1
5321927,2,0,467,0,13875,28,0
5010515,3,0,388,0,4606,23,0

In [2]:
song_listened = pd.read_csv("./data/features/C++ Output/song_listened.txt", 
                            encoding='utf-8', header=None, names=['song_listened'])

song_listened.index = train.index

train = pd.concat([train, song_listened], axis=1)
train.tail(10)

,ts_listen,context_type,media_duration,user_gender,user_id,user_age,is_listened,song_listened
1399590,1480635537,1,190,0,11367,22,1,0.524404
3515219,1480635540,1,196,1,8478,26,1,0.721623
1794123,1480635727,1,209,0,11367,22,1,0.646143
6518287,1480635742,0,276,0,17033,21,0,0.732686
235718,1480635754,0,252,0,17033,21,0,0.779660
5117944,1480635762,0,191,0,17033,21,0,0.710092
7284926,1480635790,0,182,0,17033,21,0,0.801380
1877708,1480635799,0,265,0,17033,21,0,0.690636
6190161,1480635812,0,176,0,17033,21,1,0.763809
1093339,1480635845,0,208,0,17033,21,0,-1.000000

In [3]:
# 2 - song_listened_test
path_to_test = './data/test.csv'

test = pd.read_csv(path_to_test, encoding='utf-8', usecols=cols+['ts_listen', 'user_id'])
test = test.sort_values(by=['ts_listen'], axis=0)

song_listened_test = pd.read_csv("./data/features/C++ Output/song_listened_test.txt", 
                            encoding='utf-8', header=None, names=['song_listened'])

song_listened_test.index = test.index

test = pd.concat([test, song_listened_test], axis=1)
test.head(10)

,ts_listen,context_type,media_duration,user_gender,user_id,user_age,song_listened
4089,1473680999,1,237,1,19745,27,0.772727
7094,1477679084,1,329,0,19862,27,0.848740
18287,1477763823,1,266,0,19746,23,0.637058
19589,1477829315,1,195,0,19880,25,0.481928
9995,1477929530,1,237,1,19370,19,0.764089
18127,1477931549,1,176,0,19690,26,0.618881
9127,1477938653,5,324,1,19792,26,0.782609
5255,1477945580,1,189,1,13470,27,0.706601
13976,1477945654,1,112,0,9509,21,0.000000
13927,1477959138,1,203,0,19300,21,0.585034

In [4]:
train = train.sort_index()
test = test.sort_index()
train.head()

,ts_listen,context_type,media_duration,user_gender,user_id,user_age,is_listened,song_listened
0,1480597215,12,223,0,9241,29,0,-1.0
1,1480544735,0,171,0,16547,30,1,-1.0
2,1479563953,1,149,1,7665,29,1,-1.0
3,1480152098,0,240,1,1580,30,0,-1.0
4,1478368974,0,150,1,1812,24,1,1.0

In [5]:
# 3 - cumsum
path_to_test_cumsum = './data/features/cumsum.test.csv'
path_to_train_cumsum = './data/features/cumsum.train.csv'

train_cumsum = pd.read_csv(path_to_train_cumsum, encoding='utf-8')
train = pd.concat([train, train_cumsum], axis=1)
train.head()

,ts_listen,context_type,media_duration,user_gender,user_id,user_age,is_listened,song_listened,cumsum_listen_type,cumsum_listen_type_1,cumsum_is_listened,cumsum_is_listened_1
0,1480597215,12,223,0,9241,29,0,-1.0,5.0,0.0,3.0,0.0
1,1480544735,0,171,0,16547,30,1,-1.0,4.0,0.0,1.0,1.0
2,1479563953,1,149,1,7665,29,1,-1.0,2.0,0.0,5.0,5.0
3,1480152098,0,240,1,1580,30,0,-1.0,5.0,0.0,1.0,0.0
4,1478368974,0,150,1,1812,24,1,1.0,5.0,0.0,5.0,5.0

In [6]:
test_cumsum = pd.read_csv(path_to_test_cumsum, encoding='utf-8')
test = pd.concat([test, test_cumsum], axis=1)

In [7]:
test.head()

,ts_listen,context_type,media_duration,user_gender,user_id,user_age,song_listened,cumsum_listen_type,cumsum_listen_type_1,cumsum_is_listened,cumsum_is_listened_1
0,1478104371,1,542,0,17698,30,0.666667,5.0,5.0,5.0,5.0
1,1479317140,1,307,0,10525,28,0.671202,5.0,0.0,1.0,0.0
2,1479546361,1,307,0,8716,27,0.671202,5.0,5.0,5.0,0.0
3,1478457729,1,265,0,5443,30,0.630682,5.0,0.0,1.0,0.0
4,1480448560,1,356,0,7600,29,0.733333,5.0,5.0,5.0,5.0

In [8]:
# 4 - listened before
path_to_test_prev_is_listened = './data/features/prev_is_listened.test.csv'
path_to_train_prev_is_listened = './data/features/prev_is_listened.train.csv'

train_prev_is_listened = pd.read_csv(path_to_train_prev_is_listened, encoding='utf-8')
train = pd.concat([train, train_prev_is_listened], axis=1)
train.head()

,ts_listen,context_type,media_duration,user_gender,user_id,user_age,is_listened,song_listened,cumsum_listen_type,cumsum_listen_type_1,cumsum_is_listened,cumsum_is_listened_1,was_is_listened_before
0,1480597215,12,223,0,9241,29,0,-1.0,5.0,0.0,3.0,0.0,0
1,1480544735,0,171,0,16547,30,1,-1.0,4.0,0.0,1.0,1.0,1
2,1479563953,1,149,1,7665,29,1,-1.0,2.0,0.0,5.0,5.0,1
3,1480152098,0,240,1,1580,30,0,-1.0,5.0,0.0,1.0,0.0,0
4,1478368974,0,150,1,1812,24,1,1.0,5.0,0.0,5.0,5.0,0

In [9]:
test = pd.concat([test, pd.read_csv(path_to_test_prev_is_listened, encoding='utf-8')], axis=1)
test.head()

,ts_listen,context_type,media_duration,user_gender,user_id,user_age,song_listened,cumsum_listen_type,cumsum_listen_type_1,cumsum_is_listened,cumsum_is_listened_1,was_is_listened_before
0,1478104371,1,542,0,17698,30,0.666667,5.0,5.0,5.0,5.0,1
1,1479317140,1,307,0,10525,28,0.671202,5.0,0.0,1.0,0.0,0
2,1479546361,1,307,0,8716,27,0.671202,5.0,5.0,5.0,0.0,0
3,1478457729,1,265,0,5443,30,0.630682,5.0,0.0,1.0,0.0,0
4,1480448560,1,356,0,7600,29,0.733333,5.0,5.0,5.0,5.0,0

In [10]:
# 5 - release date
path_to_release_date_train = './data/features/release_date.train.txt'
path_to_release_date_test = './data/features/release_date.test.txt'
newcols = ['release_date_listened_this_decade','release_date_listened_this_year']

train = pd.concat([train, pd.read_csv(path_to_release_date_train, encoding='utf-8', usecols=newcols)], axis=1)
train.head()

,ts_listen,context_type,media_duration,user_gender,user_id,user_age,is_listened,song_listened,cumsum_listen_type,cumsum_listen_type_1,cumsum_is_listened,cumsum_is_listened_1,was_is_listened_before,release_date_listened_this_decade,release_date_listened_this_year
0,1480597215,12,223,0,9241,29,0,-1.0,5.0,0.0,3.0,0.0,0,20,20
1,1480544735,0,171,0,16547,30,1,-1.0,4.0,0.0,1.0,1.0,1,4,1
2,1479563953,1,149,1,7665,29,1,-1.0,2.0,0.0,5.0,5.0,1,20,20
3,1480152098,0,240,1,1580,30,0,-1.0,5.0,0.0,1.0,0.0,0,20,3
4,1478368974,0,150,1,1812,24,1,1.0,5.0,0.0,5.0,5.0,0,20,5

In [11]:
test = pd.concat([test, pd.read_csv(path_to_release_date_test, encoding='utf-8', usecols=newcols)], axis=1)
test.head()

,ts_listen,context_type,media_duration,user_gender,user_id,user_age,song_listened,cumsum_listen_type,cumsum_listen_type_1,cumsum_is_listened,cumsum_is_listened_1,was_is_listened_before,release_date_listened_this_decade,release_date_listened_this_year
0,1478104371,1,542,0,17698,30,0.666667,5.0,5.0,5.0,5.0,1,14,3
1,1479317140,1,307,0,10525,28,0.671202,5.0,0.0,1.0,0.0,0,3,2
2,1479546361,1,307,0,8716,27,0.671202,5.0,5.0,5.0,0.0,0,1,1
3,1478457729,1,265,0,5443,30,0.630682,5.0,0.0,1.0,0.0,0,20,4
4,1480448560,1,356,0,7600,29,0.733333,5.0,5.0,5.0,5.0,0,20,20

In [12]:
# more Orest generated features
test['is_listened'] = 0

df = pd.concat([train, test], ignore_index=True)
df = df.sort_values(by=['user_id', 'ts_listen'], axis=0)
df.head()

,context_type,cumsum_is_listened,cumsum_is_listened_1,cumsum_listen_type,cumsum_listen_type_1,is_listened,media_duration,release_date_listened_this_decade,release_date_listened_this_year,song_listened,ts_listen,user_age,user_gender,user_id,was_is_listened_before
682493,0,0.0,0.0,0.0,0.0,1,194,1,1,-1.000000,1477939775,26,0,0,0
4454939,0,1.0,1.0,1.0,0.0,0,316,2,2,-1.000000,1477982531,26,0,0,0
5354523,0,1.0,0.0,2.0,0.0,0,224,3,3,0.724138,1477982561,26,0,0,0
5899458,0,2.0,0.0,3.0,0.0,1,210,4,4,0.766667,1477982582,26,0,0,0
4716574,0,1.0,1.0,4.0,0.0,1,185,5,5,0.717949,1477982792,26,0,0,1

In [13]:
path_to_features = './data/features/C++ Output/features.csv'
features = pd.read_csv(path_to_features, encoding='utf-8')
df = pd.concat([df, features], axis=1)
df.head()

,context_type,cumsum_is_listened,cumsum_is_listened_1,cumsum_listen_type,cumsum_listen_type_1,is_listened,media_duration,release_date_listened_this_decade,release_date_listened_this_year,song_listened,...,rank_max,rank_min,bpm_mean,bpm_std,bpm_max,bpm_min,gain_mean,gain_std,gain_max,gain_min
0,12,3.0,0.0,5.0,0.0,0,223,20,20,-1.0,...,-1.000000e+00,-1.000000e+00,-1.000,-1.00,-1.000,-1.00,-1.00000,-1.00,-1.00,-1.00
1,0,1.0,1.0,4.0,0.0,1,171,4,1,-1.0,...,1.264570e+11,2.147480e+09,2299.870,2299.87,2299.870,2299.87,29.16000,29.16,29.16,29.16
2,1,5.0,5.0,2.0,0.0,1,149,20,20,-1.0,...,2.429950e+11,2.147480e+09,599.754,17172.30,838.508,361.00,12.13000,148.84,24.01,0.25
3,0,1.0,0.0,5.0,0.0,0,240,20,3,-1.0,...,1.865660e+11,2.147480e+09,3339.370,48860.00,6393.120,1024.00,8.08667,400.00,24.01,0.00
4,0,5.0,5.0,5.0,0.0,1,150,20,5,1.0,...,3.844610e+11,2.147480e+09,2051.660,175597.00,5469.640,36.00,4.89500,702.25,12.96,1.69

In [14]:
df = df.sort_index()
train = df.loc[range(len(train))]
test = df.loc[range(len(train), len(train)+len(test))]
train.head()

,context_type,cumsum_is_listened,cumsum_is_listened_1,cumsum_listen_type,cumsum_listen_type_1,is_listened,media_duration,release_date_listened_this_decade,release_date_listened_this_year,song_listened,...,rank_max,rank_min,bpm_mean,bpm_std,bpm_max,bpm_min,gain_mean,gain_std,gain_max,gain_min
0,12,3.0,0.0,5.0,0.0,0,223,20,20,-1.0,...,-1.000000e+00,-1.000000e+00,-1.000,-1.00,-1.000,-1.00,-1.00000,-1.00,-1.00,-1.00
1,0,1.0,1.0,4.0,0.0,1,171,4,1,-1.0,...,1.264570e+11,2.147480e+09,2299.870,2299.87,2299.870,2299.87,29.16000,29.16,29.16,29.16
2,1,5.0,5.0,2.0,0.0,1,149,20,20,-1.0,...,2.429950e+11,2.147480e+09,599.754,17172.30,838.508,361.00,12.13000,148.84,24.01,0.25
3,0,1.0,0.0,5.0,0.0,0,240,20,3,-1.0,...,1.865660e+11,2.147480e+09,3339.370,48860.00,6393.120,1024.00,8.08667,400.00,24.01,0.00
4,0,5.0,5.0,5.0,0.0,1,150,20,5,1.0,...,3.844610e+11,2.147480e+09,2051.660,175597.00,5469.640,36.00,4.89500,702.25,12.96,1.69

In [15]:
test.head()

,context_type,cumsum_is_listened,cumsum_is_listened_1,cumsum_listen_type,cumsum_listen_type_1,is_listened,media_duration,release_date_listened_this_decade,release_date_listened_this_year,song_listened,...,rank_max,rank_min,bpm_mean,bpm_std,bpm_max,bpm_min,gain_mean,gain_std,gain_max,gain_min
7558834,1,5.0,5.0,5.0,5.0,0,542,14,3,0.666667,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7558835,1,1.0,0.0,5.0,0.0,0,307,3,2,0.671202,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7558836,1,5.0,0.0,5.0,5.0,0,307,1,1,0.671202,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7558837,1,1.0,0.0,5.0,0.0,0,265,20,4,0.630682,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7558838,1,5.0,5.0,5.0,5.0,0,356,20,20,0.733333,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
train.to_csv('./data/features/fat_train.csv', encoding='utf-8', index=False)
test.to_csv('./data/features/fat_test.csv', encoding='utf-8', index=False)

------

In [12]:
import pandas as pd

path_to_train = './data/features/fat_train.csv'
train = pd.read_csv(path_to_train, encoding='utf-8')

listen_type = pd.read_csv('./data/train.csv', encoding='utf-8', usecols=['listen_type'])
train = pd.concat([train, listen_type], axis=1)

path_to_train_cum_mean = './data/features/cum_mean.train.csv'
train_cum_mean = pd.read_csv(path_to_train_cum_mean, encoding='utf-8')
train = pd.concat([train, train_cum_mean], axis=1)
train.to_csv('./data/features/fat_train.csv', encoding='utf-8', index=False)

In [29]:
path_to_test = './data/features/fat_test.csv'
test = pd.read_csv(path_to_test, encoding='utf-8')

path_to_test_cum_mean = './data/features/cum_mean.test.csv'
test_cum_mean = pd.read_csv(path_to_test_cum_mean, encoding='utf-8')

test = pd.concat([test, test_cum_mean], axis=1)
test.to_csv('./data/features/fat_test.csv', encoding='utf-8', index=False)

-----

In [35]:
import validation as v
import pandas as pd
import preparation as p

path_to_train = './data/features/fat_train.csv'
train = pd.read_csv(path_to_train, encoding='utf-8')

train = p.minimal_entries_by_user(train, 2)
train.head()

,context_type,cumsum_is_listened,cumsum_is_listened_1,cumsum_listen_type,cumsum_listen_type_1,is_listened,media_duration,release_date_listened_this_decade,release_date_listened_this_year,song_listened,...,gain_min,listen_type,listen_type_cumulative_mean,genre_id_cumulative_mean,album_id_cumulative_mean,context_type_cumulative_mean,platform_name_cumulative_mean,artist_id_cumulative_mean,ts_listen_dayofweek_cumulative_mean,ts_listen_hour_cumulative_mean
0,12,3.0,0.0,5.0,0.0,0,223,20,20,-1.0,...,-1.00,0,0.705882,0.000000,0.0,0.400000,0.610063,0.000000,0.357143,0.757576
1,0,1.0,1.0,4.0,0.0,1,171,4,1,-1.0,...,29.16,0,0.625000,0.000000,0.0,0.571429,0.555556,0.000000,0.555556,0.555556
2,1,5.0,5.0,2.0,0.0,1,149,20,20,-1.0,...,0.25,1,0.994872,0.000000,0.0,0.994012,0.973333,0.000000,1.000000,1.000000
3,0,1.0,0.0,5.0,0.0,0,240,20,3,-1.0,...,0.00,0,0.701550,0.715499,0.0,0.396000,0.460227,0.787879,0.664671,0.939394
4,0,5.0,5.0,5.0,0.0,1,150,20,5,1.0,...,1.69,0,0.944444,1.000000,1.0,0.944444,0.961832,1.000000,0.863636,1.000000

In [36]:
train_index, validation_index = v.split_train_validation_by_last_record_and_flow(train)

In [37]:
list(train.columns.values)

['context_type',
 'cumsum_is_listened',
 'cumsum_is_listened_1',
 'cumsum_listen_type',
 'cumsum_listen_type_1',
 'is_listened',
 'media_duration',
 'release_date_listened_this_decade',
 'release_date_listened_this_year',
 'song_listened',
 'ts_listen',
 'user_age',
 'user_gender',
 'user_id',
 'was_is_listened_before',
 'percent_listened',
 'genre_listened',
 'album_listened',
 'artist_listened',
 'media_duration_mean',
 'media_duration_std',
 'media_duration_max',
 'media_duration_min',
 'explicit_lyrics_percent',
 'country_percent',
 'rank_mean',
 'rank_std',
 'rank_max',
 'rank_min',
 'bpm_mean',
 'bpm_std',
 'bpm_max',
 'bpm_min',
 'gain_mean',
 'gain_std',
 'gain_max',
 'gain_min',
 'listen_type',
 'listen_type_cumulative_mean',
 'genre_id_cumulative_mean',
 'album_id_cumulative_mean',
 'context_type_cumulative_mean',
 'platform_name_cumulative_mean',
 'artist_id_cumulative_mean',
 'ts_listen_dayofweek_cumulative_mean',
 'ts_listen_hour_cumulative_mean']

In [40]:
params = {
    'application':'binary',
    'num_leaves': 31,
    'max_depth': 20,
    'feature_fraction': 0.7,
    'bagging_fraction': 0.7,
    'bagging_freq': 1,
    'max_bin': 200,
    'metric': 'auc',
    'verbose': 1
}
# params = {
#     'application': 'binary',
#     'num_leaves': 255,
#     'feature_fraction': 0.7,
#     'sub_row': 0.7,
#     'bagging_freq': 1,
#     'max_bin': 255,
#     'metric': 'auc',
#     'verbose': 0,
#     'seed': 42
# }
cols = ['context_type',
 'cumsum_is_listened',
 'cumsum_is_listened_1',
 'cumsum_listen_type',
 'cumsum_listen_type_1',
 'media_duration',
 'release_date_listened_this_decade',
 'release_date_listened_this_year',
 'song_listened',
 'user_age',
 'user_gender',
 'was_is_listened_before',
 'percent_listened',
 'genre_listened',
 'album_listened',
 'artist_listened',
 'media_duration_mean',
 'media_duration_std',
 'media_duration_max',
 'media_duration_min',
 'explicit_lyrics_percent',
 'country_percent',
 'rank_mean',
 'rank_std',
 'rank_max',
 'rank_min',
 'bpm_mean',
 'bpm_std',
 'bpm_max',
 'bpm_min',
 'gain_mean',
 'gain_std',
 'gain_max',
 'gain_min',
 'user_id',
 'listen_type_cumulative_mean',
 'genre_id_cumulative_mean',
 'album_id_cumulative_mean',
 'context_type_cumulative_mean',
 'platform_name_cumulative_mean',
 'artist_id_cumulative_mean',
 'ts_listen_dayofweek_cumulative_mean',
 'ts_listen_hour_cumulative_mean']

In [ ]:
import model_lgbm as mlgbm
_, fi, model = mlgbm.crossvalidate_model_by_index(train, train_index, validation_index, cols, params, iterations=1000, validate_on_both=True)

[1]	training's auc: 0.834251	valid_1's auc: 0.684526
[2]	training's auc: 0.86069	valid_1's auc: 0.705309
[3]	training's auc: 0.859644	valid_1's auc: 0.703191
[4]	training's auc: 0.863739	valid_1's auc: 0.706983
[5]	training's auc: 0.865162	valid_1's auc: 0.707935
[6]	training's auc: 0.865564	valid_1's auc: 0.711086
[7]	training's auc: 0.865635	valid_1's auc: 0.713096
[8]	training's auc: 0.866119	valid_1's auc: 0.713442
[9]	training's auc: 0.865975	valid_1's auc: 0.712666
[10]	training's auc: 0.866503	valid_1's auc: 0.71254
[11]	training's auc: 0.866907	valid_1's auc: 0.71253
[12]	training's auc: 0.867009	valid_1's auc: 0.712374
[13]	training's auc: 0.867346	valid_1's auc: 0.712509
[14]	training's auc: 0.867585	valid_1's auc: 0.712325
[15]	training's auc: 0.867598	valid_1's auc: 0.711761
[16]	training's auc: 0.867803	valid_1's auc: 0.712344
[17]	training's auc: 0.868007	valid_1's auc: 0.712389
[18]	training's auc: 0.868207	valid_1's auc: 0.712244
[19]	training's auc: 0.868342	valid_1's auc: 0.712458
[20]	training's auc: 0.868528	valid_1's auc: 0.712747
[21]	training's auc: 0.86869	valid_1's auc: 0.713069
[22]	training's auc: 0.868806	valid_1's auc: 0.713593
[23]	training's auc: 0.868864	valid_1's auc: 0.713808
[24]	training's auc: 0.868988	valid_1's auc: 0.713721
[25]	training's auc: 0.869103	valid_1's auc: 0.714112
[26]	training's auc: 0.869201	valid_1's auc: 0.714476
[27]	training's auc: 0.86926	valid_1's auc: 0.714644
[28]	training's auc: 0.869371	valid_1's auc: 0.714605
[29]	training's auc: 0.869478	valid_1's auc: 0.714708
[30]	training's auc: 0.869545	valid_1's auc: 0.714971
[31]	training's auc: 0.869618	valid_1's auc: 0.715296
[32]	training's auc: 0.869688	valid_1's auc: 0.715483
[33]	training's auc: 0.869741	valid_1's auc: 0.715375
[34]	training's auc: 0.86984	valid_1's auc: 0.715769
[35]	training's auc: 0.869917	valid_1's auc: 0.715777
[36]	training's auc: 0.870025	valid_1's auc: 0.715802
[37]	training's auc: 0.870094	valid_1's auc: 0.715758
[38]	training's auc: 0.870197	valid_1's auc: 0.716076
[39]	training's auc: 0.870293	valid_1's auc: 0.716344
[40]	training's auc: 0.870353	valid_1's auc: 0.716461
[41]	training's auc: 0.87047	valid_1's auc: 0.717396
[42]	training's auc: 0.870539	valid_1's auc: 0.717467
[43]	training's auc: 0.870596	valid_1's auc: 0.717592
[44]	training's auc: 0.870651	valid_1's auc: 0.71775
[45]	training's auc: 0.870733	valid_1's auc: 0.717944
[46]	training's auc: 0.870785	valid_1's auc: 0.718085
[47]	training's auc: 0.870844	valid_1's auc: 0.718037
[48]	training's auc: 0.870892	valid_1's auc: 0.718157
[49]	training's auc: 0.870923	valid_1's auc: 0.718346
[50]	training's auc: 0.870975	valid_1's auc: 0.718314
[51]	training's auc: 0.871027	valid_1's auc: 0.718394
[52]	training's auc: 0.871102	valid_1's auc: 0.718815
[53]	training's auc: 0.871268	valid_1's auc: 0.719896
[54]	training's auc: 0.871331	valid_1's auc: 0.720001
[55]	training's auc: 0.871372	valid_1's auc: 0.720155
[56]	training's auc: 0.871427	valid_1's auc: 0.72015
[57]	training's auc: 0.871528	valid_1's auc: 0.720666
[58]	training's auc: 0.871593	valid_1's auc: 0.720923
[59]	training's auc: 0.871629	valid_1's auc: 0.721034
[60]	training's auc: 0.871731	valid_1's auc: 0.72228
[61]	training's auc: 0.871778	valid_1's auc: 0.722384
[62]	training's auc: 0.871809	valid_1's auc: 0.722455
[63]	training's auc: 0.871844	valid_1's auc: 0.722575
[64]	training's auc: 0.871956	valid_1's auc: 0.723653
[65]	training's auc: 0.871996	valid_1's auc: 0.723907
[66]	training's auc: 0.872034	valid_1's auc: 0.724109
[67]	training's auc: 0.872114	valid_1's auc: 0.72464
[68]	training's auc: 0.872152	valid_1's auc: 0.724731

In [ ]:
mlgbm.feature_score(fi, cols)

In [ ]:
from sklearn.metrics import roc_curve, auc
import numpy as np

y_test = np.array(train.loc[validation_index]['is_listened'])
x_test = train.loc[validation_index][cols]

y_predicted = np.array(model.predict(x_test))

# Compute ROC curve and ROC area for each class
fpr, tpr, _ = roc_curve(y_test, y_predicted)
roc_auc = auc(fpr, tpr)

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline
plt.figure()
lw = 2
plt.plot(fpr, tpr, color='darkorange',
         lw=lw, label='ROC curve (area = %0.2f)' % roc_auc)
plt.plot([0, 1], [0, 1], color='navy', lw=lw, linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver operating characteristic')
plt.legend(loc="lower right")
plt.show()

In [ ]:
import pandas as pd
import model_lgbm as mlgbm

path_to_train = './data/features/fat_train.csv'
path_to_test = './data/features/fat_test.csv'
path_to_sample = './data/sample_submission_kaggle.csv'
path_to_submission = './data/submission.csv'

train = pd.read_csv(path_to_train, encoding='utf-8')
test = pd.read_csv(path_to_test, encoding='utf-8')

fs, pred, model = mlgbm.create_submission(train, test, path_to_sample, params, cols, path_to_submission, iterations=1000)

In [ ]:
mlgbm.feature_score(fs, cols)

In [ ]:
path_to_submission_correlation = './data/vitalik_submission.csv'
previous_submission = pd.read_csv(path_to_submission_correlation, encoding='utf-8')['is_listened']

from scipy.stats.stats import pearsonr
pearsonr(pred,previous_submission)